export const BRANDS = [
  {
    name: "Las Vegas USA",
    bonus: "Up to $1,000 Welcome Bonus",
    cta: "Play at Las Vegas",
    urlDetail: "brands/phj.html",
    urlCasino: "https://phjcasino.com",
    image: "images/us/lasvegas.webp",
  },
  {
    name: "Vegas Online",
    bonus: "Exclusive bonus offers",
    cta: "Visit B Casino",
    urlDetail: "brands/b.html",
    urlCasino: "https://bcasino.com",
    image: "images/us/vegas.webp",
  },
  {
    name: "Slots and Casino",
    bonus: "Fast payouts for US players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/us/slotsandcasino.webp",
  },
  {
    name: "Ducky Luck",
    bonus: "Up to $1,000 Welcome Bonus",
    cta: "Play at PHJ Casino",
    urlDetail: "brands/phj.html",
    urlCasino: "https://phjcasino.com",
    image: "images/us/duckyluck.webp",
  },
  {
    name: "Voltage Bet",
    bonus: "Exclusive bonus offers",
    cta: "Visit B Casino",
    urlDetail: "brands/b.html",
    urlCasino: "https://bcasino.com",
    image: "images/us/voltagebet.webp",
  },
  {
    name: "Lucky Red",
    bonus: "Fast payouts for US players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/us/luckyred.webp",
  },
  {
    name: "Shazam",
    bonus: "Up to $1,000 Welcome Bonus",
    cta: "Play at PHJ Casino",
    urlDetail: "brands/phj.html",
    urlCasino: "https://phjcasino.com",
    image: "images/us/shazam.webp",
  },
  {
    name: "Lucky Tiger",
    bonus: "Exclusive bonus offers",
    cta: "Visit B Casino",
    urlDetail: "brands/b.html",
    urlCasino: "https://bcasino.com",
    image: "images/us/luckytiger.webp",
  },
  {
    name: "Rich Palms",
    bonus: "Fast payouts for US players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/us/richpalms.webp",
  }
];