export const BRANDS = [
  {
    name: "Las Vegas USA",
    bonus: "Up to $1,000 Welcome Bonus",
    cta: "Play at Las Vegas",
    urlDetail: "brands/phj.html",
    urlCasino: "https://phjcasino.com",
    image: "images/us/lasvegas.webp",
    countries: ["US"],
  },
  {
    name: "Vegas Online",
    bonus: "Exclusive bonus offers",
    cta: "Visit B Casino",
    urlDetail: "brands/b.html",
    urlCasino: "https://bcasino.com",
    image: "images/us/vegas.webp",
    countries: ["US"],
  },
  {
    name: "Slots and Casino",
    bonus: "Fast payouts for US players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/us/slotsandcasino.webp",
    countries: ["US"],
  },
  {
    name: "Ducky Luck",
    bonus: "Up to $1,000 Welcome Bonus",
    cta: "Play at PHJ Casino",
    urlDetail: "brands/phj.html",
    urlCasino: "https://phjcasino.com",
    image: "images/us/duckyluck.webp",
    countries: ["US"],
  },
  {
    name: "Voltage Bet",
    bonus: "Exclusive bonus offers",
    cta: "Visit B Casino",
    urlDetail: "brands/b.html",
    urlCasino: "https://bcasino.com",
    image: "images/us/voltagebet.webp",
    countries: ["US"],
  },
  {
    name: "Lucky Red",
    bonus: "Fast payouts for US players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/us/luckyred.webp",
    countries: ["US"],
  },
  {
    name: "Shazam",
    bonus: "Up to $1,000 Welcome Bonus",
    cta: "Play at PHJ Casino",
    urlDetail: "brands/phj.html",
    urlCasino: "https://phjcasino.com",
    image: "images/us/shazam.webp",
    countries: ["US"],
  },
  {
    name: "Lucky Tiger",
    bonus: "Exclusive bonus offers",
    cta: "Visit B Casino",
    urlDetail: "brands/b.html",
    urlCasino: "https://bcasino.com",
    image: "images/us/luckytiger.webp",
    countries: ["US"],
  },
  {
    name: "Rich Palms",
    bonus: "Fast payouts for US players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/us/richpalms.webp",
    countries: ["US"],
  },
  {
    name: "Gunsbet",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/ar/gunsbet.webp",
    countries: ["AR"],
  },
  {
    name: "Neospin",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/ar/neospin.webp",
    countries: ["AU", "CA", "CL", "NZ", "DK", "DE"],
  },
  {
    name: "Onluck",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/ar/onluck.webp",
    countries: ["AR"],
  },
  {
    name: "Evospin",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/ar/evospin.webp",
    countries: ["AR"],
  },
  
  {
    name: "1red",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/ar/1red.webp",
    countries: ["CA", "UK", "NL", "SA", "AE", "EG", "MA", "JO", "LB", "KW", "QA", "BH", "OM", "IQ", "YE", "DZ", "TN", "LY", "SD", "AT"],
  },
  {
    name: "Spinch",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/ar/spinch.webp",
    countries: ["CA", "CH", "DK", "SK", "BG", "NO", "LT", "LV", "SI", "RO", "NZ"
],
  },
  {
    name: "22Bet",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/ar/22bet.webp",
    countries: ["AR", "CL", "ES", "IT"],
  },
  // {
  //   name: "Loki",
  //   bonus: "Fast payouts for players",
  //   cta: "Play Now",
  //   urlDetail: "brands/top-slots.html",
  //   urlCasino: "https://topslots.com",
  //   image: "images/ar/loki.webp",
  //   countries: ["AR"],
  // },
  {
    name: "VBet",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/ua/vbet.webp",
    countries: ["UA"],
  },
  {
    name: "VBet",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/ua/vbet.webp",
    countries: ["UA"],
  },
  {
    name: "VBet",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/ua/vbet.webp",
    countries: ["UA"],
  },
  {
    name: "VBet",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/ua/vbet.webp",
    countries: ["UA"],
  },{
    name: "Zarbet",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/za/zarbet.webp",
    countries: ["ZA"],
  }
  ,{
    name: "Zarbet",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/za/zarbet.webp",
    countries: ["ZA"],
  },
  {
    name: "Zarbet",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/za/zarbet.webp",
    countries: ["ZA"],
  },
  {
    name: "Zarbet",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/za/zarbet.webp",
    countries: ["ZA"],
  },
  {
    name: "Crownslots",
    bonus: "Fast payouts for players",
    cta: "Play Now",
    urlDetail: "brands/top-slots.html",
    urlCasino: "https://topslots.com",
    image: "images/ar/crownslots.webp",
    countries: ["AU", "CA", "NZ", "NO", "IE", "LT", "FR", "AT", "IT", "DE"],
  }
];