export const BRANDS = [
  {
    name: 'Fortunica',
    bonus: 'Fortunica Casino features slots, fast payouts, and attractive bonuses',
    cta: 'Play now',
    urlDetail: 'brands/fortunica-uk.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120812',
    image: 'images/fortunica.webp',
    countries: ['UK'],
    top: ['UK'],
    payments: ['visa', 'mastercard', 'neteller', 'skrill', 'paysafecard'],
    isTopRated: true,
  },
  {
    name: 'Fortunica',
    bonus: 'Fortunica Casino features slots, fast payouts, and attractive bonuses',
    cta: 'Play now',
    urlDetail: 'brands/fortunica-nl.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120813',
    image: 'images/fortunica.webp',
    countries: ['NL'],
    payments: ['visa', 'mastercard', 'neteller', 'skrill', 'paysafecard'],
  },
  {
    name: 'Fortunica',
    bonus: 'Fortunica Casino features slots, fast payouts, and attractive bonuses',
    cta: 'Play now',
    urlDetail: 'brands/fortunica-es.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120814',
    image: 'images/fortunica.webp',
    countries: ['ES'],
    payments: ['visa', 'mastercard', 'neteller', 'skrill', 'paysafecard'],
  },
  {
    name: 'Qbet',
    bonus: 'Live Casino Welcome Package €300',
    cta: 'Play Now',
    urlDetail: 'brands/qbet.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120933',
    image: 'images/qbet.webp',
    countries: ['DE', 'UK', 'NO', 'FI', 'SE', 'PL', 'IE', 'PT'],
    top: ['UK'],
    payments: ['visa', 'mastercard', 'mifinity', 'googlepay', 'jeton'],
    isExclusive: true,
  },
  {
    name: 'Slots and Casino',
    bonus: '300% Welcome Match up to $1500 + 100 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/slotsandcasino.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121376',
    image: 'images/slotsandcasino.webp',
    top: ['US'],
    countries: ['US'],
    payments: ['visa', 'mastercard', 'bitcoin', 'tether', 'litecoin', 'bitcoincash', 'ethereum'],
    isTopRated: true,
  },
  {
    name: 'Chanced',
    bonus: 'Get 400% Extra Coins - Claim Welcome Offer',
    cta: 'Play Now',
    urlDetail: 'brands/chanced.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121245',
    image: 'images/chanced.webp',
    countries: ['US'],
    payments: ['visa', 'mastercard', 'americanexpress'],
  },
  {
    name: 'Las Vegas USA',
    bonus: '$20 Free Welcome Bonus',
    cta: 'Play Now',
    urlDetail: 'brands/lasvegasusa.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121273',
    image: 'images/lasvegas.webp',
    top: ['US'],
    countries: ['US'],
  },
  {
    name: 'Punt',
    bonus: '400% boost on your first purchase',
    cta: 'Play Now',
    urlDetail: 'brands/punt.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121246',
    image: 'images/punt.webp',
    countries: ['US'],
    payments: ['visa', 'mastercard', 'americanexpress'],
  },
  {
    name: 'Ducky Luck',
    bonus: 'Claim a 500% Welcome Bonus up to $2,500 + 150 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/duckyluck.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121377',
    image: 'images/duckyluck.webp',
    top: ['US'],
    countries: ['US'],
    payments: ['visa', 'mastercard', 'bitcoin', 'tether', 'litecoin', 'bitcoincash', 'ethereum'],
    isTopRated: true,
  },
  {
    name: 'Lucky Red',
    bonus: 'Get up to $4,000 400% match +$75 free chip when using Crypto',
    cta: 'Play Now',
    urlDetail: 'brands/luckyred.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=119927',
    image: 'images/luckyred.webp',
    top: ['US'],
    countries: ['US'],
    payments: ['visa', 'mastercard', 'americanexpress', 'bitcoin', 'etherium', 'litecoin', 'tether'],
    isExclusive: true,
  },
  {
    name: 'Cazino',
    bonus: 'Welcome offer get an Extra 100% in Coins',
    cta: 'Play Now',
    urlDetail: 'brands/phj.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120997',
    image: 'images/cazino.webp',
    countries: ['US'],
    payments: ['visa', 'mastercard'],
    isTopRated: true,
  },
  {
    name: 'Betlabel',
    bonus: '100% Bonus of Up to €100 for Your First Deposit',
    cta: 'Play Now',
    urlDetail: 'brands/betlabel.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121332',
    image: 'images/betlabel.svg',
    countries: [
      'CA',
      'ES',
      'IE',
      'IT',
      'GR',
      'PT',
      'CZ',
      'PL',
      'SI',
      'FI',
      'HU',
      'DE',
      'SK',
      'CH',
      'HR',
      'AT',
      'DK',
    ],
    payments: ['visa', 'mastercard', 'bitcoin', 'ethereum', 'litecoin', 'tether', 'tron'],
  },
  {
    name: 'Vegas Casino Online',
    bonus: '$20 Free Welcome Bonus',
    cta: 'Play Now',
    urlDetail: 'brands/vegas.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121272',
    image: 'images/vegas.webp',
    countries: ['US'],
    isNew: true,
  },
  {
    name: 'Gunsbet',
    bonus: 'Fast payouts for players',
    cta: 'Play Now',
    urlDetail: 'brands/gunsbet.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120679',
    image: 'images/gunsbet.webp',
    countries: ['FI', 'EE'],
    payments: ['visa', 'mastercard', 'neteller', 'skrill', 'paysafecard', 'wirecard', 'bitcoin'],
  },
  {
    name: 'Neospin',
    bonus: 'Total Welcome Pack: 300% up to €7,000 + 300 FS. Get Bonus',
    cta: 'Play Now',
    urlDetail: 'brands/neospin.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120678',
    image: 'images/neospin.webp',
    countries: ['AU', 'CA', 'CL', 'NZ', 'DK', 'DE'],
    payments: ['visa', 'ecopayz', 'neteller', 'skrill', 'mifinity'],
  },
  {
    name: 'Onluck',
    bonus: 'Bet on your favorite sports, enjoy great odds, and spin to win in exciting casino games!',
    cta: 'Play Now',
    urlDetail: 'brands/onluck.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120675',
    image: 'images/onluck.webp',
    top: ['UK'],
    countries: ['IE', 'UK', 'NL', 'DE'],
  },
  {
    name: 'Evospin',
    bonus: 'Play and win, be a little bit crazy! Fast payments. Welcome bonus up to €2,500',
    cta: 'Play Now',
    urlDetail: 'brands/evospin.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120677',
    image: 'images/evospin.webp',
    countries: ['IE', 'SI', 'SK', 'AT', 'NL', 'DE'],
  },

  {
    name: '1red',
    bonus: 'Welcome pack 200% up to €9,300 + 100 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/1red.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120680',
    image: 'images/1red.webp',
    countries: [
      'CA',
      'UK',
      'NL',
      'SA',
      'AE',
      'EG',
      'MA',
      'JO',
      'LB',
      'KW',
      'QA',
      'BH',
      'OM',
      'IQ',
      'YE',
      'DZ',
      'TN',
      'LY',
      'SD',
      'AT',
    ],
    top: ['UK'],
    payments: ['visa', 'mastercard', 'neteller', 'jeton', 'neosurf', 'skrill', 'maestro'],
  },
  {
    name: 'Spinch',
    bonus: 'Welcome Pack 225% up to €6,000 + 250 FS',
    cta: 'Play Now',
    urlDetail: 'brands/spinch.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120681',
    image: 'images/spinch.webp',
    countries: ['CA', 'CH', 'DK', 'SK', 'BG', 'NO', 'LT', 'LV', 'SI', 'RO', 'NZ'],
    payments: ['visa', 'ecopayz', 'neteller', 'skrill', 'mifinity'],
  },
  {
    name: '22Bet',
    bonus: 'Fast payouts for players',
    cta: 'Play Now',
    urlDetail: 'brands/22bet.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121242',
    image: 'images/22bet.webp',
    countries: [
      'AR',
      'CA',
      'FI',
      'IN',
      'NG',
      'RO',
      'CL',
      'CH',
      'AT',
      'CO',
      'DE',
      'IE',
      'SK',
      'UZ',
      'HR',
      'GH',
      'IT',
      'PL',
      'SI',
      'CZ',
      'PT',
      'DK',
      'HU',
      'PE',
      'UG',
      'BG',
      'KE',
      'ES',
    ],
    payments: ['visa', 'mastercard'],
  },
  {
    name: 'Loki',
    bonus: 'Welcome Bonus 255% up to €6,000 + 230 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/loki.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120674',
    image: 'images/loki.webp',
    countries: ['NU', 'HO', 'SI', 'HR', 'AT', 'UK'],
  },
  // {
  //   name: 'VBet',
  //   bonus: 'No deposit: 25 free spins, no wagering, for verification',
  //   cta: 'Play Now',
  //   urlDetail: 'brands/vbet.html',
  //   urlCasino: '#',
  //   image: 'images/vbet.webp',
  //   countries: ['UA'],
  //   payments: ['visa', 'applepay', 'googlepay'],
  // },
  {
    name: 'BetOn Casino',
    bonus: 'For new players: 250,000 ₴ + 500 free spins',
    cta: 'Play Now',
    urlDetail: 'brands/beton.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121024',
    image: 'images/beton.webp',
    countries: ['UA'],
    payments: ['visa', 'mastercard', 'applepay', 'googlepay'],
    isTopRated: true,
  },
  {
    name: 'BetOn Sport',
    bonus: 'Welcome Bonus 200% up to 200,000 ₴',
    cta: 'Play Now',
    urlDetail: 'brands/beton.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121025',
    image: 'images/beton.webp',
    countries: ['UA'],
    payments: ['visa', 'mastercard', 'applepay', 'googlepay'],
  },
  {
    name: 'Fugu Casino',
    bonus: 'Sign up and get a welcome bonus up to 250% + 500 FS',
    cta: 'Play Now',
    urlDetail: 'brands/fugu.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120899',
    image: 'images/fugu.webp',
    countries: ['RU', 'KZ', 'UA'],
    payments: ['visa', 'mastercard', 'mifinity', 'jeton', 'applepay'],
  },
  // {
  //   name: 'Zarbet',
  //   bonus: 'Fast payouts for players',
  //   cta: 'Play Now',
  //   urlDetail: 'brands/top-slots.html',
  //   urlCasino: 'https://topslots.com',
  //   image: 'images/zarbet.webp',
  //   countries: ['ZA'],
  // },
  {
    name: 'Crownslots',
    bonus: 'Welcome Pack 400% up to €4,000 + 250 FS. Get Bonus',
    cta: 'Play Now',
    urlDetail: 'brands/crownslots.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120673',
    image: 'images/crownslots.webp',
    countries: ['AU', 'CA', 'NZ', 'NO', 'IE', 'LT', 'FR', 'AT', 'IT', 'DE'],
    top: ['AU'],
    payments: ['visa', 'mastercard', 'ecopayz', 'bitcoin', 'ethereum', 'neteller', 'skrill', 'mifinity'],
    hasDetailPage: true,
  },
  {
    name: 'Corgibet',
    bonus: 'Play games and get 15% cashback every week!',
    cta: 'Play Now',
    urlDetail: 'brands/corgibet.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120783',
    image: 'images/corgibet.webp',
    countries: [
      'ES',
      'DE',
      'AT',
      'CH',
      'IT',
      'CZ',
      'GR',
      'BE',
      'PL',
      'FR',
      'AU',
      'SK',
      'SI',
      'HU',
      'PT',
      'CA',
      'DK',
      'IE',
      'NO',
      'AL',
      'ME',
      'RS',
    ],
    top: ['AU'],
    payments: ['visa', 'mastercard', 'googlepay', 'applepay', 'bitcoin', 'ethereum'],
  },
  {
    name: 'Spinbetter',
    bonus: 'Get 200% + 150 FS no wager on your first 4 deposits!',
    cta: 'Play Now',
    urlDetail: 'brands/spinbetter.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121023',
    image: 'images/spinbetter.webp',
    countries: [
      'PL',
      'PT',
      'DE',
      'ES',
      'TR',
      'CH',
      'BE',
      'SK',
      'HU',
      'AT',
      'CZ',
      'FI',
      'GR',
      'LV',
      'DK',
      'SE',
      'IE',
      'NO',
      'EE',
      'MD',
      'SI',
      'AL',
      'MK',
      'IS',
      'RU',
      'KZ',
      'UZ',
      'KG',
      'EG',
      'BJ',
      'TZ',
      'LK',
      'IN',
      'BD',
      'PH',
      'PK',
      'BR',
    ],
    top: ['BR'],
    payments: ['bitcoin', 'ethereum', 'bitcoincash', 'cardano', 'litecoin', 'tether', 'tron'],
  },
  {
    name: 'Coolzino',
    bonus: 'Welcome Package: up to €1,500 + 250 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/coolzino.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120782',
    image: 'images/coolzino.webp',
    countries: ['IT', 'GR', 'BE', 'PL', 'AU', 'CH', 'AT', 'NO', 'DK', 'PT', 'IE', 'CA', 'NZ'],
    top: ['AU'],
    payments: ['visa', 'mastercard', 'googlepay', 'applepay', 'ethereum', 'bitcoin'],
  },
  {
    name: 'Magnetic Slots',
    bonus: 'Fast payouts for players',
    cta: 'Play Now',
    urlDetail: 'brands/magneticslots.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120784',
    image: 'images/magneticslots.webp',
    countries: [
      'ES',
      'DE',
      'IT',
      'BE',
      'AT',
      'CZ',
      'LU',
      'PL',
      'GR',
      'DK',
      'HU',
      'SK',
      'SI',
      'FI',
      'CA',
      'AU',
    ],
    top: ['AU'],
    payments: ['visa', 'mastercard', 'googlepay', 'applepay', 'bitcoin', 'ethereum'],
  },
  {
    name: 'Beef Casino',
    bonus: 'Fast payouts for players',
    cta: 'Play Now',
    urlDetail: 'brands/beef.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120895',
    image: 'images/beef.webp',
    countries: ['RU', 'KZ'],
    payments: ['visa', 'mastercard', 'mifinity', 'jeton', 'applepay', 'googlepay'],
  },
  {
    name: 'Sol Casino',
    bonus: 'Fast payouts for players',
    cta: 'Play Now',
    urlDetail: 'brands/sol.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120892',
    image: 'images/sol.webp',
    countries: ['RU', 'KZ'],
  },
  {
    name: 'Lex Casino',
    bonus: 'Fast payouts for players',
    cta: 'Play Now',
    urlDetail: 'brands/lex.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120888',
    image: 'images/lex.webp',
    countries: ['RU', 'KZ'],
  },
  {
    name: 'Legzo Casino',
    bonus: 'Fast payouts for players',
    cta: 'Play Now',
    urlDetail: 'brands/legzo.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120894',
    image: 'images/legzo.webp',
    countries: ['RU', 'KZ'],
  },
  {
    name: 'Izzi Casino',
    bonus: 'Fast payouts for players',
    cta: 'Play Now',
    urlDetail: 'brands/izzi.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120890',
    image: 'images/izzi.webp',
    countries: ['RU', 'KZ'],
  },
  {
    name: 'Irwin Casino',
    bonus: 'Fast payouts for players',
    cta: 'Play Now',
    urlDetail: 'brands/irwin.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120897',
    image: 'images/irwin.webp',
    countries: ['RU', 'KZ'],
  },
  {
    name: 'Gizbo Casino',
    bonus: 'Fast payouts for players',
    cta: 'Play Now',
    urlDetail: 'brands/gizbo.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120893',
    image: 'images/gizbo.webp',
    countries: ['RU', 'KZ'],
  },
  {
    name: 'Fresh Casino',
    bonus: 'Fast payouts for players',
    cta: 'Play Now',
    urlDetail: 'brands/fresh.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120889',
    image: 'images/fresh.webp',
    countries: ['RU', 'KZ'],
  },
  {
    name: 'Martin Casino',
    bonus: 'Fast payouts for players',
    cta: 'Play Now',
    urlDetail: 'brands/martin.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120896',
    image: 'images/martin.webp',
    countries: ['RU', 'KZ'],
  },
  {
    name: 'Drip Casino',
    bonus: 'Fast payouts for players',
    cta: 'Play Now',
    urlDetail: 'brands/drip.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120891',
    image: 'images/drip.webp',
    countries: ['RU', 'KZ'],
  },
  {
    name: 'Flagman',
    bonus: 'Fast payouts for players',
    cta: 'Play Now',
    urlDetail: 'brands/flagman.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120898',
    image: 'images/flagman.webp',
    countries: ['UZ'],
  },
  {
    name: 'Betwinner',
    bonus: 'Bonus for sports.  Casino + Win Games',
    cta: 'Play Now',
    urlDetail: 'brands/betwinner.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120928',
    image: 'images/betwinner.webp',
    countries: [
      'DZ',
      'AR',
      'AM',
      'AZ',
      'BD',
      'BJ',
      'BO',
      'BF',
      'CM',
      'CL',
      'CO',
      'CR',
      'CD',
      'EC',
      'EG',
      'SV',
      'GA',
      'GH',
      'GT',
      'GN',
      'GW',
      'HN',
      'IN',
      'IR',
      'CI',
      'KZ',
      'KE',
      'KG',
      'MY',
      'ML',
      'MX',
      'MA',
      'MZ',
      'NP',
      'NI',
      'NG',
      'PK',
      'PY',
      'PE',
      'PH',
      'CG',
      'RU',
      'SN',
      'SO',
      'ZA',
      'LK',
      'TJ',
      'TZ',
      'TG',
      'TR',
      'UG',
      'UY',
      'UZ',
      'VE',
      'ZM',
    ],
    payments: ['visa', 'mastercard', 'applepay', 'googlepay', 'bci', 'ecopayz', 'webmoney'],
  },
  {
    name: '30Bet',
    bonus: 'Casino welcome offer. Claim your €300 now. + 50 free spins',
    cta: 'Play Now',
    urlDetail: 'brands/30bet.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120929',
    image: 'images/30bet.webp',
    countries: ['DE', 'UK', 'NO', 'FI', 'SE'],
    payments: ['visa', 'mastercard', 'neteller', 'jeton', 'mifinity', 'skrill'],
  },
  {
    name: '55Bet',
    bonus: 'Casino welcome offer. 100% up to 100 EUR',
    cta: 'Play Now',
    urlDetail: 'brands/55bet.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120930',
    image: 'images/55bet.webp',
    countries: ['DE', 'NO', 'FI', 'SE'],
    payments: ['visa', 'mastercard', 'neteller', 'jeton', 'mifinity', 'googlepay', 'flexepin', 'skrill'],
  },
  {
    name: 'GQbet',
    bonus: 'Claim up to €500/£500 and enjoy 5% live casino cashback',
    cta: 'Play Now',
    urlDetail: 'brands/gqbet.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120931',
    image: 'images/gqbet.webp',
    countries: ['UK', 'FR'],
    payments: ['visa', 'mastercard', 'neteller', 'skrill'],
  },
  {
    name: '1RedBet',
    bonus: 'Welcome Bonus: 100% up to 200,000 CLP on first deposit',
    cta: 'Play Now',
    urlDetail: 'brands/1redbet.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121287',
    image: 'images/1redbet.webp',
    countries: ['AT', 'CH', 'CA', 'DE', 'IT', 'CZ', 'PL', 'HU'],
    top: ['CA'],
    payments: ['litecoin', 'ethereum', 'bitcoin', 'tron'],
    isTopRated: true,
  },
  {
    name: 'Manga',
    bonus: '100% bonus up to €250 play live & get more credits!',
    cta: 'Play Now',
    urlDetail: 'brands/manga.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=120932',
    image: 'images/manga.webp',
    countries: ['DE', 'NO', 'FI', 'SE'],
  },
  {
    name: 'ViciBet',
    bonus: 'Start Strong with a 325% UP TO €3,000 + 300 FS!',
    cta: 'Play Now',
    urlDetail: 'brands/vicibet.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121286',
    image: 'images/vicibet.webp',
    countries: ['PL', 'NO', 'FI', 'BE', 'HU', 'AT', 'CH', 'CZ', 'IT', 'DE', 'CA'],
    payments: ['visa', 'mastercard', 'jeton', 'bitcoin', 'litecoin', 'bitcoincash', 'cordano'],
  },
  {
    name: 'Casino Infinity',
    bonus: 'Welcome Bonus: 10% Cashback on your first deposit',
    cta: 'Play Now',
    urlDetail: 'brands/casinoinfinity.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121288',
    image: 'images/casinoinfinity.png',
    countries: ['PL', 'NO', 'FI', 'BE', 'HU', 'AT', 'CH', 'CZ', 'IT', 'DE', 'CA'],
    payments: ['mastercard', 'jeton', 'mifinity', 'ethereum', 'bitcoin', 'bitcoincash', 'litecoin', 'tether'],
  },
  {
    name: 'Roletto',
    bonus: 'Welcome Bonus - Sports 150% + 200 Free Bets',
    cta: 'Play Now',
    urlDetail: 'brands/roletto.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121065',
    image: 'images/roletto.webp',
    countries: ['UK', 'DE', 'SE', 'NO', 'IT', 'FR', 'CA', 'AT', 'CH', 'FI', 'BR', 'PT', 'DK', 'ES'],
    top: ['CA'],
    payments: ['visa', 'mastercard', 'jeton', 'mifinity', 'ethereum', 'bitcoin', 'litecoin', 'tether'],
  },
  {
    name: 'Vegas Now',
    bonus: 'Up to 8,000 €/$ + 500 free spins',
    cta: 'Play Now',
    urlDetail: 'brands/vegasnow.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121066',
    image: 'images/vegasnow.webp',
    countries: ['AU', 'CA', 'NZ', 'AT', 'CH', 'IE', 'NO', 'SE', 'FI', 'DK', 'IS'],
    payments: ['visa', 'mastercard', 'bitcoin', 'neteller', 'skrill'],
  },
  {
    name: 'Lukki',
    bonus: 'Claim your Welcome Bonus Up to 4,000 €/s + 300 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/lukki.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121067',
    image: 'images/lukki.webp',
    countries: ['AU', 'CA', 'NZ', 'AT', 'CH', 'IE', 'NO', 'SE', 'FI', 'DK', 'IS'],
    payments: ['visa', 'mastercard', 'bitcoin'],
  },
  {
    name: 'Lets Lucky',
    bonus: '4,500 € Welcome Offer + 300 FS',
    cta: 'Play Now',
    urlDetail: 'brands/letslucky.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121068',
    image: 'images/letslucky.svg',
    countries: ['AU', 'CA', 'NZ', 'AT', 'CH', 'IE', 'NO', 'SE', 'FI', 'DK', 'IS'],
    payments: ['visa', 'mastercard', 'bitcoin', 'bitcoincash', 'tether'],
    isNew: true,
  },
  {
    name: 'Lucky Dreams',
    bonus: 'Enjoy up to 10,000 € bonus + 500 free spins',
    cta: 'Play Now',
    urlDetail: 'brands/luckydreams.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121069',
    image: 'images/luckydreams.webp',
    countries: ['AU', 'CA', 'NZ', 'AT', 'CH', 'IE', 'NO', 'SE', 'FI', 'DK', 'IS'],
    payments: ['visa', 'mastercard', 'neteller', 'mifinity', 'bitcoin', 'bitcoincash', 'skrill', 'tether'],
  },
  {
    name: 'Lucky Ones',
    bonus: 'Welcome Offer: Up to €20,000 Bonus + 500 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/luckyones.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121070',
    image: 'images/luckyones.webp',
    countries: ['AU', 'CA', 'NZ', 'AT', 'CH', 'IE', 'NO', 'SE', 'FI', 'DK', 'IS'],
    payments: ['visa', 'mastercard', 'neteller', 'bitcoin'],
  },
  {
    name: 'Just Casino',
    bonus: '5,000 €/$ + 400 free spins, Nothing but Casino',
    cta: 'Play Now',
    urlDetail: 'brands/justcasino.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121071',
    image: 'images/justcasino.webp',
    countries: ['AU', 'CA', 'NZ', 'AT', 'CH', 'IE', 'NO', 'SE', 'FI', 'DK', 'IS'],
    top: ['CA'],
    payments: ['visa', 'mastercard', 'bitcoin'],
  },
  {
    name: 'BetPari',
    bonus: 'Get a 100% bonus of up to 100 EUR for your first deposit!',
    cta: 'Play Now',
    urlDetail: 'brands/betpari.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121120',
    image: 'images/betpari.webp',
    countries: [
      'PT',
      'RO',
      'HU',
      'TR',
      'LT',
      'GR',
      'SI',
      'IS',
      'NL',
      'IE',
      'LU',
      'NO',
      'CH',
      'DE',
      'AR',
      'EG',
      'UZ',
      'BJ',
      'TZ',
      'TG',
      'KE',
      'CI',
      'NE',
      'UG',
      'NG',
      'BF',
    ],
    payments: ['cardano', 'ethereum', 'bitcoin', 'tron'],
  },
  {
    name: 'Pantherbet',
    bonus: 'First Deposit Bonus - 100% Up to R3 000',
    cta: 'Play Now',
    urlDetail: 'brands/pantherbet.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121161',
    image: 'images/pantherbet.webp',
    countries: ['ZA'],
    payments: ['visa', 'mastercard', 'applepay'],
    isTopRated: true,
  },
  {
    name: 'NV Casino',
    bonus: 'Welcome Package - Up to €2,000 + 225 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/nvcasono.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121162',
    image: 'images/nvcasono.webp',
    countries: [
      'PL',
      'EE',
      'LT',
      'LV',
      'GR',
      'RO',
      'HU',
      'BE',
      'SK',
      'NO',
      'DK',
      'SE',
      'LU',
      'IS',
      'BA',
      'AL',
      'ME',
      'HR',
      'BG',
      'DE',
    ],
    payments: ['visa', 'mastercard', 'neteller', 'mifinity', 'skrill'],
  },
  {
    name: 'Yep Casino',
    bonus: 'Welcome Package - Up to €3,000 + 300 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/yepcasino.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121163',
    image: 'images/yepcasino.webp',
    countries: [
      'PL',
      'EE',
      'LT',
      'LV',
      'GR',
      'RO',
      'HU',
      'BE',
      'SK',
      'NO',
      'DK',
      'SE',
      'LU',
      'IS',
      'BA',
      'AL',
      'ME',
      'HR',
      'BG',
      'DE',
    ],
    payments: ['visa', 'mastercard', 'neteller', 'mifinity', 'skrill'],
    isExclusive: true,
  },
  {
    name: 'Ripper Casino',
    bonus: 'Grab Your 20 Free Spins + $7,500 Welcome Bonus',
    cta: 'Play Now',
    urlDetail: 'brands/ripper.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121279',
    image: 'images/ripper.png',
    countries: ['US'],
  },
  {
    name: 'Zizobet',
    bonus: 'Welcome Bonus - 550% Up to €3,800 + 50 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/zizobet.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121164',
    image: 'images/zizobet.webp',
    countries: [
      'AR',
      'AU',
      'AT',
      'AZ',
      'BE',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'HR',
      'CZ',
      'DK',
      'EG',
      'EE',
      'FI',
      'FR',
      'DE',
      'GH',
      'GR',
      'HU',
      'IS',
      'IN',
      'ID',
      'IE',
      'IT',
      'JP',
      'KZ',
      'KE',
      'LV',
      'LT',
      'LU',
      'MY',
      'MX',
      'NL',
      'NZ',
      'NG',
      'NO',
      'PH',
      'PL',
      'PT',
      'PE',
      'RU',
      'RO',
      'SG',
      'SK',
      'SI',
      'ZA',
      'KR',
      'ES',
      'SE',
      'CH',
      'TH',
      'TR',
      'TZ',
      'UG',
      'UA',
      'UK',
      'US',
      'UZ',
      'VN',
    ],
    top: ['BR'],
    payments: [
      'visa',
      'mastercard',
      'applepay',
      'googlepay',
      'jeton',
      'bitcoin',
      'mifinity',
      'ethereum',
      'litecoin',
    ],
    isNew: true,
  },
  {
    name: 'Ozwin Casino',
    bonus: 'Grab Your 20 Free Spins + $7,500 Welcome Bonus',
    cta: 'Play Now',
    urlDetail: 'brands/ozwin.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121280',
    image: 'images/ozwin.png',
    countries: ['US'],
    payments: ['visa', 'mastercard', 'applepay', 'googlepay', 'bitcoin', 'tether'],
  },
  {
    name: 'Wonaco',
    bonus: 'Casino Welcome Package - Up to €2,500 in 3 Bonuses + 1 Bonus Crab',
    cta: 'Play Now',
    urlDetail: 'brands/wonaco.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121177',
    image: 'images/wonaco.webp',
    countries: ['AU', 'IT', 'DE', 'CZ', 'IE', 'CH', 'CA', 'SK', 'AT', 'PL', 'FI', 'NO', 'HU'],
    payments: ['mastercard', 'applepay', 'googlepay', 'jeton', 'bitcoin', 'mifinity', 'ethereum', 'litecoin'],
  },
  {
    name: 'Dolly Casino',
    bonus: 'Welcome Package - 225% Up to €1,000',
    cta: 'Play Now',
    urlDetail: 'brands/dollycasino.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121178',
    image: 'images/dollycasino.webp',
    countries: ['AU', 'IT', 'DE', 'CZ', 'IE', 'CH', 'CA', 'SK', 'AT', 'PL', 'FI', 'NO', 'HU'],
    top: ['CA'],
    payments: [
      'bitcoincash',
      'mastercard',
      'cardano',
      'jeton',
      'bitcoin',
      'mifinity',
      'ethereum',
      'litecoin',
    ],
  },
  {
    name: 'Velobet',
    bonus: 'Welcome casino package 330% + 300 free spins guaranteed!',
    cta: 'Play Now',
    urlDetail: 'brands/velobet.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121179',
    image: 'images/velobet.png',
    countries: [
      'AR',
      'AU',
      'AT',
      'AZ',
      'BE',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'HR',
      'CZ',
      'DK',
      'EG',
      'EE',
      'FI',
      'FR',
      'DE',
      'GH',
      'GR',
      'HU',
      'IS',
      'IN',
      'ID',
      'IE',
      'IT',
      'JP',
      'KZ',
      'KE',
      'LV',
      'LT',
      'LU',
      'MY',
      'MX',
      'NL',
      'NZ',
      'NG',
      'NO',
      'PH',
      'PL',
      'PT',
      'PE',
      'RU',
      'RO',
      'SG',
      'SK',
      'SI',
      'ZA',
      'KR',
      'ES',
      'SE',
      'CH',
      'TH',
      'TR',
      'TZ',
      'UG',
      'UA',
      'UK',
      'US',
      'UZ',
      'VN',
    ],
    top: ['BR'],
    payments: ['visa', 'mastercard', 'skrill', 'neteller', 'bitcoin', 'tether', 'ethereum', 'litecoin'],
  },
  {
    name: 'Casino Peaches',
    bonus: '100% Welcome Bonus up to €1,000 on Your First Deposit',
    cta: 'Play Now',
    urlDetail: 'brands/casinopeaches.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121220',
    image: 'images/casinopeaches.png',
    countries: ['UK', 'IE', 'NL', 'SE', 'ES', 'IT', 'DE'],
  },
  {
    name: 'Casino Peaches',
    bonus: '250% Welcome Bonus up to €1,000',
    cta: 'Play Now',
    urlDetail: 'brands/casinopeaches-fr.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121221',
    image: 'images/casinopeaches.png',
    countries: ['FR'],
  },
  {
    name: "Let's Jackpot",
    bonus: '100% Welcome Bonus up to €4,000 on Your First Deposit',
    cta: 'Play Now',
    urlDetail: 'brands/letsjackpot.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121222',
    image: 'images/letsjackpot.svg',
    countries: ['UK', 'IE', 'IT', 'NL', 'SE', 'BE', 'DK', 'ES', 'FI', 'MK', 'MT', 'NO', 'PT', 'SK'],
  },
  {
    name: "Let's Jackpot",
    bonus: '100% Welcome Bonus up to €2,004 on Your First Deposit',
    cta: 'Play Now',
    urlDetail: 'brands/letsjackpot-fr.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121223',
    image: 'images/letsjackpot.svg',
    countries: ['FR'],
  },
  {
    name: 'Uspin',
    bonus: 'Casino Welcome Bonus - Up to €5,000 + 350 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/uspin.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121224',
    image: 'images/uspin.png',
    countries: ['UK', 'NL', 'DE', 'AT', 'CH'],
  },
  {
    name: 'Uspin',
    bonus: 'Casino Welcome Bonus - Up to €5,000 + 350 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/uspin-fr.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121225',
    image: 'images/uspin.png',
    countries: ['FR'],
  },
  {
    name: 'Zumibet',
    bonus: '100% Welcome Bonus up to $5,000 on Your First Deposit',
    cta: 'Play Now',
    urlDetail: 'brands/zumibet.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121227',
    image: 'images/zumibet.png',
    countries: ['AU'],
  },
  {
    name: 'Amon Casino',
    bonus: '100% Welcome Bonus up to €500 on Your First Deposit',
    cta: 'Play Now',
    urlDetail: 'brands/amon.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121228',
    image: 'images/amon.png',
    countries: ['FR'],
  },
  {
    name: 'Betzino',
    bonus: '200% Welcome Bonus up to €200 on Your First Deposit',
    cta: 'Play Now',
    urlDetail: 'brands/betzino.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121229',
    image: 'images/betzino.png',
    countries: ['UK', 'IE'],
  },
  {
    name: 'Betzino',
    bonus: '200% Welcome Bonus up to €200 on Your First Deposit',
    cta: 'Play Now',
    urlDetail: 'brands/betzino-fr.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121230',
    image: 'images/betzino.png',
    countries: ['FR'],
  },
  {
    name: 'BOF Casino',
    bonus: '100% Welcome Bonus up to €1,000 on Your First Deposit',
    cta: 'Play Now',
    urlDetail: 'brands/bof.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121231',
    image: 'images/bof.svg',
    countries: ['UK', 'IE'],
  },
  {
    name: 'Azurslot',
    bonus: 'Welcome Package 250% up to €1,500 + 250 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/azurslot.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121330',
    image: 'images/azurslot.svg',
    countries: [
      'AU',
      'AT',
      'CA',
      'CZ',
      'DK',
      'FI',
      'DE',
      'GR',
      'IT',
      'NZ',
      'NO',
      'PL',
      'ES',
      'SE',
      'CH',
      'PT',
    ],
  },
  {
    name: 'Winairlines',
    bonus: 'Welcome Package up to €1,500 + 250 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/winairlines.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121243',
    image: 'images/winairlines.webp',
    countries: [
      'BE',
      'DE',
      'ES',
      'IT',
      'AT',
      'CH',
      'GR',
      'RS',
      'AL',
      'ME',
      'MK',
      'HU',
      'PL',
      'AU',
      'NZ',
      'DK',
      'CA',
      'RO',
      'PT',
      'LU',
      'IE',
      'HR',
      'FI',
      'SK',
      'SI',
      'CZ',
      'BR',
      'NO',
    ],
    top: ['BR'],
    payments: ['visa', 'mastercard', 'applepay', 'googlepay', 'bitcoin', 'ethereum', 'litecoin'],
    isNew: true,
  },
  {
    name: 'SlotsPlus',
    bonus: '$20 Free Welcome Bonus',
    cta: 'Play Now',
    urlDetail: 'brands/slotsplus.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121244',
    image: 'images/slotsplus.png',
    countries: ['US'],
    isExclusive: true,
  },
  {
    name: 'Sun Palace',
    bonus: '$20 Free Welcome Bonus',
    cta: 'Play Now',
    urlDetail: 'brands/sunpalace.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121278',
    image: 'images/sunpalace.png',
    countries: ['US'],
  },
  {
    name: 'Fair Go',
    bonus: 'Up to $1,000 Welcome Bonus. Fast Payouts and Real Wins',
    cta: 'Play Now',
    urlDetail: 'brands/fairgo.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121281',
    image: 'images/fairgo.png',
    countries: ['US'],
    payments: ['visa', 'mastercard', 'applepay', 'googlepay', 'bitcoin', 'tether', 'litecoin', 'bitcoincash'],
  },
  {
    name: 'Red Stag',
    bonus: '$2,500 Bonus + 500 Free Spins',
    cta: 'Play Now',
    urlDetail: 'brands/redstag.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121282',
    image: 'images/redstag.png',
    countries: ['US'],
  },
  {
    name: 'Slots Capital',
    bonus: '600% Bonus on Your First Crypto Deposit',
    cta: 'Play Now',
    urlDetail: 'brands/slotscapital.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121283',
    image: 'images/slotscapital.png',
    countries: ['US'],
    payments: ['visa', 'mastercard', 'bitcoin', 'litecoin', 'bitcoincash'],
  },
  {
    name: 'Uptown Aces',
    bonus: 'New in Uptown? Grab Your $10 Welcome Bonus!',
    cta: 'Play Now',
    urlDetail: 'brands/uptownaces.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121284',
    image: 'images/uptownaces.png',
    countries: ['US'],
    payments: ['visa', 'mastercard', 'bitcoin', 'litecoin', 'bitcoincash', 'tether'],
  },
  {
    name: 'Safe Casino',
    bonus: 'Welcome package 100% up to €4000 + 1200 Free spins',
    cta: 'Play Now',
    urlDetail: 'brands/safecasino.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121335',
    image: 'images/safecasino.png',
    countries: ['AU', 'CA', 'NZ', 'DE', 'AT', 'ES', 'PL', 'CZ', 'PT', 'IT', 'GR', 'HU'],
    payments: ['visa', 'mastercard'],
  },
  {
    name: '22bit',
    bonus: 'Welcome Package Up To 17,000 USDT',
    cta: 'Play Now',
    urlDetail: 'brands/22bit.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121331',
    image: 'images/22bit.svg',
    countries: [
      'AU',
      'CA',
      'NZ',
      'DE',
      'AT',
      'ES',
      'PL',
      'CZ',
      'PT',
      'IT',
      'GR',
      'HU',
      'FI',
      'CH',
      'DK',
      'NO',
      'SE',
      'SI',
      'KR',
      'JP',
      'IE',
      'HR',
    ],
  },
  {
    name: 'KoiFortune',
    bonus: 'Get Up to 2700$ + 200 FS for a Great Start',
    cta: 'Play Now',
    urlDetail: 'brands/koifortune.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121333',
    image: 'images/koifortune.svg',
    countries: ['KR', 'JP'],
    payments: [
      'visa',
      'mastercard',
      'applepay',
      'googlepay',
      'bitcoin',
      'tether',
      'litecoin',
      'bitcoincash',
      'tron',
      'ethereum',
    ],
  },
  {
    name: '22Casino',
    bonus: 'Welcome package up to 1500 EUR + 150 FS',
    cta: 'Play Now',
    urlDetail: 'brands/22casino.html',
    urlCasino: 'https://armadaapp.media-412.com/click?pid=3862&offer_id=121334',
    image: 'images/22casino.svg',
    countries: ['AU', 'CZ', 'FI', 'GR', 'HU', 'IT', 'PT', 'ES', 'CH'],
  },
];
